config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index'

  resources :items do
    resources :packs
  end

  get 'get_price' => 'price#accept_and_return_combo'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
    has_many :packs, dependent: :destroy
    validates :item_name, :item_code, presence: true
end

app/models/pack.rb
class Pack < ApplicationRecord
  belongs_to :item
  validates :quantity, :price, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @items = Item.all
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]

  # GET /items or /items.json
  def index
    @items = Item.all
  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_path, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:item_name, :item_code)
    end
end

app/controllers/packs_controller.rb
class PacksController < ApplicationController
  before_action :get_item
  before_action :set_pack, only: %i[ show edit update destroy ]

  # GET /packs or /packs.json
  def index
    # @packs = Pack.all
    @packs = @item.packs
  end

  # GET /packs/1 or /packs/1.json
  def show
  end

  # GET /packs/new
  def new
    # @pack = Pack.new
    @pack = @item.packs.build
  end

  # GET /packs/1/edit
  def edit
  end

  # POST /packs or /packs.json
  def create
    @pack = @item.packs.build(pack_params)

    respond_to do |format|
      if @pack.save
        format.html { redirect_to item_packs_path(@item), notice: "Pack was successfully created." }
        format.json { render :show, status: :created, location: @pack }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pack.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /packs/1 or /packs/1.json
  def update
    respond_to do |format|
      if @pack.update(pack_params)
        format.html { redirect_to item_packs_path(@item), notice: "Pack was successfully updated." }
        format.json { render :show, status: :ok, location: @pack }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pack.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /packs/1 or /packs/1.json
  def destroy
    @pack.destroy
    respond_to do |format|
      format.html { redirect_to item_packs_path, notice: "Pack was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def get_item
    @item = Item.find(params[:item_id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pack
      @pack = Pack.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pack_params
      params.require(:pack).permit(:quantity, :price)
      # params.fetch(:pack, {})
    end
end

app/controllers/price_controller.rb
class PriceController < ApplicationController

  #STEP 1 GET AND RETURN DATA TO VIEW
  def accept_and_return_combo
    @item_id = params[:item_id]
    @item_code = params[:item_code]
    @quantity = params[:quantity]
    quantity = params[:quantity]
    @details = Item.find(params[:item_id])
    details = @details
    quantity_array = []

    details.packs.each do |list|
      quantity_array.push(list.quantity)
    end

    @array = quantity_array
    @best_combo = make_combo(quantity.to_i, quantity_array)
    best_combo = @best_combo

    @total_breakdown = total_breakdown(details, best_combo)
    @calculation = calculate_price(details, best_combo)

    respond_to do |format|
      format.html { redirect_to root_path }
      format.js { render partial: 'home/price_result' }
    end
  end

  #STEP 2 GENERATE THE BEST COMBINATION
  def make_combo(quantity, combination_of_packs)
    #sort combination_of_packs from max to min
    combination_of_packs.sort! { |a, b| b <=> a }
    # memoize solutions
    optimal_combo = Hash.new do |hash, key|
    p hash
    p key
    hash[key] = if key < combination_of_packs.min
          []
      elsif combination_of_packs.include?(key)
          [key]
      else
          combination_of_packs.
          reject { |pack| pack > key }.
          inject([]) {|mem, var| mem.any? {|c| c%var == 0} ? mem : mem+[var]}.
          # recurse
          map { |pack| [pack] + hash[key - pack] }.
          # prune unhelpful solutions
          reject { |change| change.sum != key }.
          # pick the smallest, empty if none
          min { |a, b| a.size <=> b.size } || []
      end
    end
    optimal_combo[quantity]
  end

  #STEP 3 GET THE TOTAL BREAKDOWN
  def total_breakdown(details, best_combo)
    packs_hash = {}
    combo_tally = best_combo.tally
    calculation_breakdown_array = []

    details.packs.map do |value|
      packs_hash[value.quantity] = value.price.to_f
    end

    total = 0
    combo_tally.each do |pack, tally|
      tally_singular_or_plural = tally == 1 ? " pack of " : " packs of "
      breakdown_string = tally.to_s + tally_singular_or_plural + pack.to_s + " = " + (packs_hash[pack] * tally).to_s
      calculation_breakdown_array.push(breakdown_string)
    end
    calculation_breakdown_array
  end

  def calculate_price(details, best_combo)
    packs_hash = {}
    combo_tally = best_combo.tally

    details.packs.map do |value|
      packs_hash[value.quantity] = value.price.to_f
    end

    total = 0
    combo_tally.each do |pack, tally|
      total += packs_hash[pack] * tally
    end
    total
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/packs_helper.rb
module PacksHelper
end

app/views/home/_price_result.html.erb
<div class="card text-dark p-2" id="result">
  <h1>Code: <%= @item_code %></h1>
  <h1 class="mb-3">Qty: <%= @quantity %></h1>
  <h3>Breakdown</h3>
  <% @total_breakdown.each do |breakdown| %>
    <p><%= breakdown %></p>
  <% end %>
  <h1 class="mt-1">Total: </h1>
  <h1><%= number_to_currency(@calculation) %></h1>
</div>

app/views/home/_price_result.js.erb
document.querySelector('#price_result').innerHTML = '<%= escape_javascript(render 'home/price_result.html') %>'

app/views/home/index.html.erb
<h3>Welcome to</h3>
<h3>Panaderya ni Aling Nena™ Packs Calculator</h3>
<p>An App for per packs price calculation</p>
<%= link_to 'Add Products', items_path, class: "btn btn-warning btn-lg w-25 mx-auto mt-2" %>
<div class="container p-5">
  <div class="row">
    <% @items.each do |item| %>
      <div class="col-sm-12 col-md-6 col-lg-3">
        <div class="card-deck">
          <div class="card">
            <%= image_tag ('bread.svg'), class: "card-img-top" %>
            <div class="card-body">
              <h5 class="card-title"><%= item.item_name %></h5>
              <h5 class="card-title"><%= item.item_code %></h5>
              <% quantity_array=[] %>
              <% item.packs.each do |list| %>
                <% quantity_array.push(list.quantity) %>
                <h6><%= list.quantity %> for <%= number_to_currency(list.price)%></h6>
              <% end %>
              <%= form_tag get_price_path, id: item.item_code, remote: true, method: :get do %>
                <%= hidden_field_tag :item_id, item.id %>
                <%= hidden_field_tag :item_code, item.item_code %>
                <%= number_field_tag :quantity, params[:quantity], placeholder: 'Enter Quantity', min: '1', max: '100', class: "form-control" %>
                <%= button_tag "Get Price", class: "btn btn-primary mt-2 mt-3" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <div class="col-sm-12 col-md-6 col-lg-3">
      <div id="price_result">
      </div>
    </div>
  </div>
</div>

app/views/items/_form.html.erb
<%= form_with(model: item) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :item_name %>
    <%= form.text_field :item_name %>
  </div>

  <div class="field">
    <%= form.label :item_code %>
    <%= form.text_field :item_code %>
  </div>

  <div class="actions">
    <%= form.submit "New item", class: "btn btn-warning btn-lg w-25 mx-auto" %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %>
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>
<div class="text-center">
  <h1>Breads</h1>
  <hr>
</div>
<table>
  <thead>
    <tr>
      <th>Item name</th>
      <th>Item code</th>
      <th>
        <ul style="list-style-type:none;">
          <li>
            <p>Packs</p>
          </li>
        </ul>
      </th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.item_name %></td>
        <td><%= item.item_code %></td>
        <td>
          <ul style="list-style-type:none;">
            <% item.packs.each do |list| %>
              <li><%= list.quantity %> for <%= number_to_currency(list.price)%></li>
            <% end %>
          </ul>
        </td>
        <td><%= link_to 'Add Packs', item_packs_path(item), class: "btn btn-sm btn-success" %></td>
        <td><%= link_to 'Edit', edit_item_path(item), class: "btn btn-sm btn-primary" %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Item', new_item_path, class: "btn btn-warning btn-lg w-25 mx-auto mb-2" %>
<%= link_to 'Back', root_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item name:</strong>
  <%= @item.item_name %>
</p>

<p>
  <strong>Item code:</strong>
  <%= @item.item_code %>
</p>

<%= link_to 'Edit', edit_item_path(@item), class: "btn btn-warning btn-lg w-25 mx-auto mb-2" %>
<%= link_to 'Back', items_path, class: "btn btn-warning btn-lg w-25 mx-auto" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Panaderya ni Aling Nena</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="cover-container d-flex w-70 h-100 p-1 mx-auto flex-column">
      <%= yield %>
    </div>
  </body>
</html>

app/views/packs/_form.html.erb
<%= form_with model: [@item,@pack] do |form| %>
  <% if pack.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pack.errors.count, "error") %> prohibited this pack from being saved:</h2>

      <ul>
        <% pack.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, step: :any %>
  </div>

  <div class="actions">
    <%= form.submit "New pack", class: "btn btn-warning btn-lg w-25 mx-auto" %>
  </div>
<% end %>

app/views/packs/edit.html.erb
<h1>Editing Pack</h1>

<%= render 'form', pack: @pack %>

<%= link_to 'Back', item_packs_path %>

app/views/packs/index.html.erb
<p id="notice"><%= notice %></p>
<h1><%=@item.item_name%> Packs</h1>
<p><%=@item.item_code%></p>
<p>Note: Please add price for single orders (Quantity 1), if you want to sell per piece.</p>
<hr>
<table>
  <thead>
    <tr>
      <th>Quantity</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @packs.each do |pack| %>
      <tr>
        <td><%= pack.quantity %></td>
        <td><%= number_to_currency(pack.price) %></td>
        <td><%= link_to 'Edit', edit_item_pack_path(:id => pack.id), class: "btn btn-sm btn-primary" %></td>
        <td><%= link_to 'Destroy', item_pack_path(:id => pack.id), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Pack', new_item_pack_path, class: "btn btn-warning btn-lg w-25 mx-auto mb-2" %>
<%= link_to 'Back', items_path %>

app/views/packs/new.html.erb
<h1>New Pack</h1>

<%= render 'form', pack: @pack %>

<%= link_to 'Back', item_packs_path %>

app/views/packs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_pack_path(@pack) %> |
<%= link_to 'Back', item_packs_path %>